### ISSUE TITLE
Improve the text's drafting.

### ISSUE THREAD

**Issue by aeromero2** [Practicum42-MP-20201/tarea1-ensayo-de-analisis-Carmenjara#1]
`Ahora bien, mi trabajo de titulación está enfocado a la automatización del proceso de mantenimiento de la flota vehicular de la Policía Nacional Sub-Zona 7. Considerando el caos que hay ante un pandemia, los servicios de transportación hospitalaria y atención médica necesitan gestionar de forma adecuada la logística de sus unidades, así como el estado de las mismas para no parar su utilización de forma prolongada por no haber realizado el mantenimiento correspondiente dentro del límite de kilometraje de acuerdo al tipo de unidad de salud. 
`
- El texto está correcto respecto de los párrafos que se han identificado: la idea general del texto, el resumen de la película y el aporte del TT.

Considere también mejorar esto:

- Hablar en modo impersonal, evite las expresiones *mi, nosotros*

- *Considerando el caos que hay ante un pandemia, los servicios de transportación hospitalaria y atención médica necesitan gestionar de forma adecuada la logística de sus unidades,*  Mejore la expresión de esta idea.

**Comment by Carmenjara** [comment]
Correciones aplicadas, espero su revisión y comentarios. Gracias!

**Comment by aeromero2** [comment]
De acuerdo Rocío! Cerramos el issue! misión  cumplida!
